branches:
    only:
        - master
language: php
php:
    - 5.4
    - 5.5
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
    - java -jar selenium-server-standalone-2.31.0.jar > /dev/null 2>&1 &
    - echo "github.com,207.97.227.239 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ" >> ~/.ssh/known_hosts
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs
    - composer --dev --prefer-source install
    - php -Slocalhost:8000 -tweb > /dev/null 2>&1 &
    - bin/console user:add admin admin
script:
    - node_modules/.bin/coffeelint -f config/ci/coffeelint.json -r resources/coffee
    - php -l src
    - bin/behat
