branches:
    only:
        - master
language: php
php:
    - 5.4
    - 5.5
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
    - java -jar selenium-server-standalone-2.31.0.jar > /dev/null 2>&1 &
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs
    - composer --dev --no-interaction install
    - php -Slocalhost:8000 -tweb > /dev/null 2>&1 &
    - bin/console user:add admin admin
script:
    - node_modules/.bin/coffeelint -f config/ci/coffeelint.json -r resources/coffee
    - php -l src
    - bin/behat
